site_name: clj-fakes
site_description: Project documentation for clj-fakes framework.

repo_url: https://github.com/metametadata/clj-fakes/

theme: cinder

pages:
- Readme: 'index.md'
- Quickstart: 'quickstart.md'
- User Guide: 'user-guide.md'
- API Reference: 'api/index.md'
- Developer Guide: 'dev-guide.md'
